/* Payroll Transaction list (Sprint 2) - demo data.
 *
 * GENERATED by facilitator/tools/generate-data.js. Do not hand-edit.
 *
 * Deterministic by design: every value is hard-coded. No Math.random(), no
 * new Date(). Amounts are integer oere, formatted by fmtAmount() in app.js.
 */

var EMPLOYEES = [
  { no: '1042', name: 'Anna Berg' },
  { no: '1077', name: 'Lars Haugen' },
  { no: '1103', name: 'Ingrid Solberg' },
  { no: '1128', name: 'Ola Nilsen' },
  { no: '1154', name: 'Kari Dahl' },
  { no: '1189', name: 'Per Johansen' },
  { no: '1205', name: 'Hanne Lie' },
  { no: '1233', name: 'Jonas Moe' },
  { no: '1250', name: 'Sofie Bakken' },
  { no: '1276', name: 'Erik Strand' },
  { no: '1302', name: 'Maria Lund' },
  { no: '1331', name: 'Thomas Aas' },
  { no: '1357', name: 'Nora Eide' },
  { no: '1384', name: 'Henrik Vik' },
  { no: '1410', name: 'Emma Holm' }
];

var RUNS = [
  { id: '2026-03', label: 'March 2026', state: 'Closed', paidOn: '25.03.2026' },
  { id: '2026-04', label: 'April 2026', state: 'Closed', paidOn: '24.04.2026' },
  { id: '2026-05', label: 'May 2026', state: 'Open', paidOn: 'not yet paid' },
  { id: '2026-06', label: 'June 2026', state: 'Open', paidOn: 'not yet paid' }
];

var DEFAULT_RUN = '2026-06';

/* The demo clock. Edits and rejections are stamped from here, one minute per
 * action, so the audit trail reads the same on every laptop. */
var DEMO_CLOCK = { date: '16.06.2026', hour: 9, minute: 0 };

function audit(createdBy, createdAt, changedBy, changedAt) {
  return { createdBy: createdBy, createdAt: createdAt, changedBy: changedBy,
           changedAt: changedAt, events: [] };
}

var TRANSACTIONS = [
  /* ---------- June 2026 run: 60 transactions, 15 employees, 4 each ---------- */

  { id: 'T-1101', run: '2026-06', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Salary', period: '2026-06', amount: 5200000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1102', run: '2026-06', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Overtime', period: '2026-06', amount: 390000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('anna.berg', '10.06.2026 13:41', null, null) },

  { id: 'T-1103', run: '2026-06', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Deduction', period: '2026-06', amount: -150000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1104', run: '2026-06', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Reimbursement', period: '2026-06', amount: 145000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('anna.berg', '06.06.2026 15:55', null, null) },

  { id: 'T-1105', run: '2026-06', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Salary', period: '2026-06', amount: 4850000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1106', run: '2026-06', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Overtime', period: '2026-06', amount: 410000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('lars.haugen', '08.06.2026 08:09', null, null) },

  { id: 'T-1107', run: '2026-06', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Deduction', period: '2026-06', amount: -180000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1108', run: '2026-06', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Overtime', period: '2026-05', amount: -120000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: { id: 'T-1005', run: '2026-05', label: 'May 2026' },
    error: null,
    audit: audit('payroll.admin', '10.06.2026 14:05', null, null) },

  { id: 'T-1109', run: '2026-06', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-06', amount: 6100000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1110', run: '2026-06', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Overtime', period: '2026-06', amount: 260000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('ingrid.solberg', '06.06.2026 12:37', null, null) },

  { id: 'T-1111', run: '2026-06', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Deduction', period: '2026-06', amount: -240000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1112', run: '2026-06', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-05', amount: 275000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Pending', severity: null,
    retroOf: { id: 'T-1007', run: '2026-05', label: 'May 2026' },
    error: null,
    audit: audit('payroll.admin', '10.06.2026 14:05', null, null) },

  { id: 'T-1113', run: '2026-06', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Salary', period: '2026-06', amount: 4500000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1114', run: '2026-06', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Overtime', period: '2026-06', amount: 185000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('ola.nilsen', '10.06.2026 16:05', null, null) },

  { id: 'T-1115', run: '2026-06', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Deduction', period: '2026-06', amount: -220000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1116', run: '2026-06', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Reimbursement', period: '2026-06', amount: 76000, costCenter: 'CC-200',
    projectCode: '', account: '7140', status: 'Error', severity: 'warning',
    retroOf: null,
    error: {
      reason: 'No receipt attached. This can still be paid, but it will be flagged in the audit.',
      rule: 'Receipt required above 500,00',
      actual: '760,00 with no receipt attached',
      fixLabel: 'Open the reimbursement and attach a receipt'
    },
    audit: audit('ola.nilsen', '06.06.2026 09:19', null, null) },

  { id: 'T-1117', run: '2026-06', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Salary', period: '2026-06', amount: 5500000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1118', run: '2026-06', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Overtime', period: '2026-06', amount: 560000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5010', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'Overtime is above the monthly limit in this employee contract.',
      rule: 'Maximum overtime per month: 5 000,00',
      actual: '5 600,00 registered for June 2026',
      fixLabel: 'Open the overtime registration for Kari Dahl'
    },
    audit: audit('kari.dahl', '08.06.2026 11:33', null, null) },

  { id: 'T-1119', run: '2026-06', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Deduction', period: '2026-06', amount: -190000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1120', run: '2026-06', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Reimbursement', period: '2026-06', amount: 230000, costCenter: 'CC-300',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('kari.dahl', '10.06.2026 13:47', null, null) },

  { id: 'T-1121', run: '2026-06', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Salary', period: '2026-06', amount: 4950000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1122', run: '2026-06', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Overtime', period: '2026-06', amount: 330000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('per.johansen', '06.06.2026 15:01', null, null) },

  { id: 'T-1123', run: '2026-06', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Deduction', period: '2026-06', amount: -340000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1124', run: '2026-06', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Reimbursement', period: '2026-06', amount: 98000, costCenter: 'CC-300',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('per.johansen', '08.06.2026 08:15', null, null) },

  { id: 'T-1125', run: '2026-06', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Salary', period: '2026-06', amount: 5800000, costCenter: 'CC-100',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1126', run: '2026-06', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Overtime', period: '2026-06', amount: 440000, costCenter: 'CC-100',
    projectCode: 'PRJ-C', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('hanne.lie', '10.06.2026 10:29', null, null) },

  { id: 'T-1127', run: '2026-06', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Deduction', period: '2026-06', amount: -290000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1128', run: '2026-06', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Reimbursement', period: '2026-06', amount: 125000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('hanne.lie', '06.06.2026 12:43', null, null) },

  { id: 'T-1129', run: '2026-06', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Salary', period: '2026-06', amount: 4300000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1130', run: '2026-06', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Overtime', period: '2026-06', amount: 290000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('jonas.moe', '08.06.2026 14:57', null, null) },

  { id: 'T-1131', run: '2026-06', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Deduction', period: '2026-06', amount: -95000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1132', run: '2026-06', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Overtime', period: '2026-05', amount: -40000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: { id: 'T-1023', run: '2026-05', label: 'May 2026' },
    error: null,
    audit: audit('payroll.admin', '10.06.2026 14:05', null, null) },

  { id: 'T-1133', run: '2026-06', employeeNo: '1250', employeeName: 'Sofie Bakken',
    type: 'Salary', period: '2026-06', amount: 4700000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5000', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1134', run: '2026-06', employeeNo: '1250', employeeName: 'Sofie Bakken',
    type: 'Overtime', period: '2026-06', amount: 220000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('sofie.bakken', '06.06.2026 09:25', null, null) },

  { id: 'T-1135', run: '2026-06', employeeNo: '1250', employeeName: 'Sofie Bakken',
    type: 'Deduction', period: '2026-06', amount: -160000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1136', run: '2026-06', employeeNo: '1250', employeeName: 'Sofie Bakken',
    type: 'Reimbursement', period: '2026-06', amount: 64000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('sofie.bakken', '08.06.2026 11:39', null, null) },

  { id: 'T-1137', run: '2026-06', employeeNo: '1276', employeeName: 'Erik Strand',
    type: 'Salary', period: '2026-06', amount: 5350000, costCenter: 'CC-200',
    projectCode: 'PRJ-B', account: '5000', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'The employee has no active bank account, so the payment cannot be sent.',
      rule: 'An active bank account is required before payment',
      actual: 'No active account since 31.05.2026',
      fixLabel: 'Open the bank details for Erik Strand'
    },
    audit: audit('system.import', '02.06.2026 04:10', 'payroll.admin', '09.06.2026 10:02') },

  { id: 'T-1138', run: '2026-06', employeeNo: '1276', employeeName: 'Erik Strand',
    type: 'Overtime', period: '2026-06', amount: 370000, costCenter: 'CC-200',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('erik.strand', '10.06.2026 13:53', null, null) },

  { id: 'T-1139', run: '2026-06', employeeNo: '1276', employeeName: 'Erik Strand',
    type: 'Deduction', period: '2026-06', amount: -210000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1140', run: '2026-06', employeeNo: '1276', employeeName: 'Erik Strand',
    type: 'Reimbursement', period: '2026-06', amount: 110000, costCenter: 'CC-200',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('erik.strand', '06.06.2026 15:07', null, null) },

  { id: 'T-1141', run: '2026-06', employeeNo: '1302', employeeName: 'Maria Lund',
    type: 'Salary', period: '2026-06', amount: 5050000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1142', run: '2026-06', employeeNo: '1302', employeeName: 'Maria Lund',
    type: 'Overtime', period: '2026-06', amount: 140000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('maria.lund', '08.06.2026 08:21', null, null) },

  { id: 'T-1143', run: '2026-06', employeeNo: '1302', employeeName: 'Maria Lund',
    type: 'Deduction', period: '2026-06', amount: -170000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1144', run: '2026-06', employeeNo: '1302', employeeName: 'Maria Lund',
    type: 'Reimbursement', period: '2026-06', amount: 1000000, costCenter: 'CC-200',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('maria.lund', '10.06.2026 10:35', null, null) },

  { id: 'T-1145', run: '2026-06', employeeNo: '1331', employeeName: 'Thomas Aas',
    type: 'Salary', period: '2026-06', amount: 4650000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5000', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1146', run: '2026-06', employeeNo: '1331', employeeName: 'Thomas Aas',
    type: 'Overtime', period: '2026-06', amount: 275000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5010', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('thomas.aas', '06.06.2026 12:49', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1147', run: '2026-06', employeeNo: '1331', employeeName: 'Thomas Aas',
    type: 'Deduction', period: '2026-06', amount: -135000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1148', run: '2026-06', employeeNo: '1331', employeeName: 'Thomas Aas',
    type: 'Reimbursement', period: '2026-06', amount: 920000, costCenter: 'CC-300',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('thomas.aas', '08.06.2026 14:03', null, null) },

  { id: 'T-1149', run: '2026-06', employeeNo: '1357', employeeName: 'Nora Eide',
    type: 'Salary', period: '2026-06', amount: 5100000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1150', run: '2026-06', employeeNo: '1357', employeeName: 'Nora Eide',
    type: 'Overtime', period: '2026-06', amount: 315000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('nora.eide', '10.06.2026 16:17', null, null) },

  { id: 'T-1151', run: '2026-06', employeeNo: '1357', employeeName: 'Nora Eide',
    type: 'Deduction', period: '2026-06', amount: -205000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1152', run: '2026-06', employeeNo: '1357', employeeName: 'Nora Eide',
    type: 'Reimbursement', period: '2026-06', amount: 87000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Error', severity: 'warning',
    retroOf: null,
    error: {
      reason: 'No receipt attached. This can still be paid, but it will be flagged in the audit.',
      rule: 'Receipt required above 500,00',
      actual: '870,00 with no receipt attached',
      fixLabel: 'Open the reimbursement and attach a receipt'
    },
    audit: audit('nora.eide', '06.06.2026 09:31', null, null) },

  { id: 'T-1153', run: '2026-06', employeeNo: '1384', employeeName: 'Henrik Vik',
    type: 'Salary', period: '2026-06', amount: 4400000, costCenter: 'CC-200',
    projectCode: 'PRJ-A', account: '5000', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'No valid tax card on file, so tax cannot be calculated.',
      rule: 'A valid tax card is required before payment',
      actual: 'No tax card received for 2026',
      fixLabel: 'Open the tax card page for Henrik Vik'
    },
    audit: audit('system.import', '02.06.2026 04:10', 'payroll.admin', '09.06.2026 10:02') },

  { id: 'T-1154', run: '2026-06', employeeNo: '1384', employeeName: 'Henrik Vik',
    type: 'Overtime', period: '2026-06', amount: 195000, costCenter: 'CC-200',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('henrik.vik', '08.06.2026 11:45', null, null) },

  { id: 'T-1155', run: '2026-06', employeeNo: '1384', employeeName: 'Henrik Vik',
    type: 'Deduction', period: '2026-06', amount: -125000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1156', run: '2026-06', employeeNo: '1384', employeeName: 'Henrik Vik',
    type: 'Reimbursement', period: '2026-06', amount: 41000, costCenter: 'CC-200',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('henrik.vik', '10.06.2026 13:59', null, null) },

  { id: 'T-1157', run: '2026-06', employeeNo: '1410', employeeName: 'Emma Holm',
    type: 'Salary', period: '2026-06', amount: 5650000, costCenter: 'CC-300',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', 'hanne.lie', '08.06.2026 11:20') },

  { id: 'T-1158', run: '2026-06', employeeNo: '1410', employeeName: 'Emma Holm',
    type: 'Overtime', period: '2026-06', amount: 405000, costCenter: 'CC-300',
    projectCode: 'PRJ-C', account: '5010', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('emma.holm', '06.06.2026 15:13', null, null) },

  { id: 'T-1159', run: '2026-06', employeeNo: '1410', employeeName: 'Emma Holm',
    type: 'Deduction', period: '2026-06', amount: -260000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Pending', severity: null,
    retroOf: null,
    error: null,
    audit: audit('system.import', '02.06.2026 04:10', null, null) },

  { id: 'T-1160', run: '2026-06', employeeNo: '1410', employeeName: 'Emma Holm',
    type: 'Reimbursement', period: '2026-06', amount: 190000, costCenter: 'CC-300',
    projectCode: '', account: '7140', status: 'Approved', severity: null,
    retroOf: null,
    error: null,
    audit: audit('emma.holm', '08.06.2026 08:27', 'hanne.lie', '08.06.2026 11:20') },

  /* ---------- May 2026 run: 24 transactions, 8 employees, 3 each ---------- */

  { id: 'T-1001', run: '2026-05', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Salary', period: '2026-05', amount: 5200000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'hanne.lie', '06.05.2026 11:42') },

  { id: 'T-1002', run: '2026-05', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Overtime', period: '2026-05', amount: 430000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: null, error: null,
    audit: audit('hanne.lie', '11.05.2026 09:05', null, null) },

  { id: 'T-1003', run: '2026-05', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Reimbursement', period: '2026-05', amount: 125000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('anna.berg', '08.05.2026 16:20', 'jonas.moe', '12.05.2026 08:55') },

  { id: 'T-1004', run: '2026-05', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Salary', period: '2026-05', amount: 4850000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'hanne.lie', '06.05.2026 11:42') },

  { id: 'T-1005', run: '2026-05', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Overtime', period: '2026-05', amount: 620000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5010', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'Overtime is above the monthly limit in this employee contract.',
      rule: 'Maximum overtime per month: 5 000,00',
      actual: '6 200,00 registered for May 2026',
      fixLabel: 'Open the overtime registration for Lars Haugen'
    },
    audit: audit('lars.haugen', '09.05.2026 17:31', null, null) },

  { id: 'T-1006', run: '2026-05', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Deduction', period: '2026-05', amount: -180000, costCenter: 'CC-100',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', null, null) },

  { id: 'T-1007', run: '2026-05', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-05', amount: 6100000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'No valid tax card on file, so tax cannot be calculated.',
      rule: 'A valid tax card is required before payment',
      actual: 'No tax card received for 2026',
      fixLabel: 'Open the tax card page for Ingrid Solberg'
    },
    audit: audit('system.import', '02.05.2026 04:10', 'payroll.admin', '13.05.2026 10:02') },

  { id: 'T-1008', run: '2026-05', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Overtime', period: '2026-05', amount: 240000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5010', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('ingrid.solberg', '10.05.2026 12:44', 'hanne.lie', '12.05.2026 09:10') },

  { id: 'T-1009', run: '2026-05', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-03', amount: 350000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Pending', severity: null,
    retroOf: { id: 'T-0903', run: '2026-03', label: 'March 2026' },
    error: null,
    audit: audit('payroll.admin', '12.05.2026 14:08', null, null) },

  { id: 'T-1010', run: '2026-05', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Salary', period: '2026-05', amount: 4500000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'hanne.lie', '06.05.2026 11:42') },

  { id: 'T-1011', run: '2026-05', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Deduction', period: '2026-05', amount: -220000, costCenter: 'CC-200',
    projectCode: '', account: '5290', status: 'Pending', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', null, null) },

  { id: 'T-1012', run: '2026-05', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Reimbursement', period: '2026-05', amount: 89000, costCenter: 'CC-200',
    projectCode: '', account: '7140', status: 'Error', severity: 'warning',
    retroOf: null,
    error: {
      reason: 'No receipt attached. This can still be paid, but it will be flagged in the audit.',
      rule: 'Receipt required above 500,00',
      actual: '890,00 with no receipt attached',
      fixLabel: 'Open the reimbursement and attach a receipt'
    },
    audit: audit('ola.nilsen', '07.05.2026 13:26', null, null) },

  { id: 'T-1013', run: '2026-05', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Salary', period: '2026-05', amount: 5500000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'hanne.lie', '06.05.2026 11:42') },

  { id: 'T-1014', run: '2026-05', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Overtime', period: '2026-05', amount: 310000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: null, error: null,
    audit: audit('kari.dahl', '11.05.2026 08:12', null, null) },

  { id: 'T-1015', run: '2026-05', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Overtime', period: '2026-04', amount: 190000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5010', status: 'Pending', severity: null,
    retroOf: { id: 'T-0985', run: '2026-04', label: 'April 2026' },
    error: null,
    audit: audit('payroll.admin', '12.05.2026 14:15', null, null) },

  { id: 'T-1016', run: '2026-05', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Salary', period: '2026-05', amount: 4950000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'hanne.lie', '06.05.2026 11:42') },

  { id: 'T-1017', run: '2026-05', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Deduction', period: '2026-05', amount: -340000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'jonas.moe', '09.05.2026 15:37') },

  { id: 'T-1018', run: '2026-05', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Reimbursement', period: '2026-05', amount: 215000, costCenter: 'CC-300',
    projectCode: '', account: '7140', status: 'Pending', severity: null,
    retroOf: null, error: null,
    audit: audit('per.johansen', '10.05.2026 07:48', null, null) },

  { id: 'T-1019', run: '2026-05', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Salary', period: '2026-05', amount: 5800000, costCenter: 'CC-100',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', 'payroll.admin', '06.05.2026 11:42') },

  { id: 'T-1020', run: '2026-05', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Overtime', period: '2026-05', amount: 480000, costCenter: 'CC-100',
    projectCode: 'PRJ-C', account: '5010', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'The employee has no active bank account, so the payment cannot be sent.',
      rule: 'An active bank account is required before payment',
      actual: 'No active account since 30.04.2026',
      fixLabel: 'Open the bank details for Hanne Lie'
    },
    audit: audit('hanne.lie', '11.05.2026 10:19', null, null) },

  { id: 'T-1021', run: '2026-05', employeeNo: '1205', employeeName: 'Hanne Lie',
    type: 'Reimbursement', period: '2026-05', amount: 64000, costCenter: 'CC-100',
    projectCode: '', account: '7140', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('hanne.lie', '05.05.2026 09:33', 'jonas.moe', '12.05.2026 08:55') },

  { id: 'T-1022', run: '2026-05', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Salary', period: '2026-05', amount: 4300000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Pending', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', null, null) },

  { id: 'T-1023', run: '2026-05', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Overtime', period: '2026-05', amount: 540000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5010', status: 'Error', severity: 'blocking',
    retroOf: null,
    error: {
      reason: 'Overtime is above the monthly limit in this employee contract.',
      rule: 'Maximum overtime per month: 5 000,00',
      actual: '5 400,00 registered for May 2026',
      fixLabel: 'Open the overtime registration for Jonas Moe'
    },
    audit: audit('jonas.moe', '10.05.2026 18:02', null, null) },

  { id: 'T-1024', run: '2026-05', employeeNo: '1233', employeeName: 'Jonas Moe',
    type: 'Deduction', period: '2026-05', amount: -95000, costCenter: 'CC-300',
    projectCode: '', account: '5290', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.05.2026 04:10', null, null) },

  /* ---------- March 2026 run (closed) — exists so the run list is a real flow ---------- */

  { id: 'T-0901', run: '2026-03', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Salary', period: '2026-03', amount: 5100000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  { id: 'T-0902', run: '2026-03', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Salary', period: '2026-03', amount: 4850000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  { id: 'T-0903', run: '2026-03', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-03', amount: 5750000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  { id: 'T-0904', run: '2026-03', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Salary', period: '2026-03', amount: 4500000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  { id: 'T-0905', run: '2026-03', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Salary', period: '2026-03', amount: 5500000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  { id: 'T-0906', run: '2026-03', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Salary', period: '2026-03', amount: 4950000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.03.2026 04:10', 'hanne.lie', '06.03.2026 10:21') },

  /* ---------- April 2026 run (closed) ---------- */

  { id: 'T-0981', run: '2026-04', employeeNo: '1042', employeeName: 'Anna Berg',
    type: 'Salary', period: '2026-04', amount: 5200000, costCenter: 'CC-100',
    projectCode: 'PRJ-A', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.04.2026 04:10', 'hanne.lie', '07.04.2026 09:55') },

  { id: 'T-0982', run: '2026-04', employeeNo: '1077', employeeName: 'Lars Haugen',
    type: 'Salary', period: '2026-04', amount: 4850000, costCenter: 'CC-100',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.04.2026 04:10', 'hanne.lie', '07.04.2026 09:55') },

  { id: 'T-0983', run: '2026-04', employeeNo: '1103', employeeName: 'Ingrid Solberg',
    type: 'Salary', period: '2026-04', amount: 6100000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.04.2026 04:10', 'hanne.lie', '07.04.2026 09:55') },

  { id: 'T-0984', run: '2026-04', employeeNo: '1128', employeeName: 'Ola Nilsen',
    type: 'Salary', period: '2026-04', amount: 4500000, costCenter: 'CC-200',
    projectCode: 'PRJ-C', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.04.2026 04:10', 'hanne.lie', '07.04.2026 09:55') },

  { id: 'T-0985', run: '2026-04', employeeNo: '1154', employeeName: 'Kari Dahl',
    type: 'Overtime', period: '2026-04', amount: 280000, costCenter: 'CC-300',
    projectCode: 'PRJ-A', account: '5010', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('kari.dahl', '09.04.2026 16:40', 'hanne.lie', '14.04.2026 11:02') },

  { id: 'T-0986', run: '2026-04', employeeNo: '1189', employeeName: 'Per Johansen',
    type: 'Salary', period: '2026-04', amount: 4950000, costCenter: 'CC-300',
    projectCode: 'PRJ-B', account: '5000', status: 'Approved', severity: null,
    retroOf: null, error: null,
    audit: audit('system.import', '02.04.2026 04:10', 'hanne.lie', '07.04.2026 09:55') }
];
